### ISSUE TITLE
Question: multiple mkPython

### ISSUE THREAD

**Issue by tartavull** [DavHau/mach-nix#116]
Is is possible to call mkPython multiple times by passing a name?

**Comment by DavHau** [comment]
Not sure exactly what you mean by that. Could you provide some more details on what you're planning to do?

**Comment by tartavull** [comment]
Thanks @DavHau!
```
mach-nix.mkPython {
    requirements = ''

      # mbed-cli
      mbed-cli
      pip
      pyyaml
      jsonschema
      jinja2
      mbed_cloud_sdk
      pyelftools
      mbed_ls
      manifest_tool
      pycryptodome
      pyusb
      psutil
      click

      # ROS
      rosdep
      rosinstall-generator
      vcstool
      rosinstall
      setuptools
      empy
    '';
```

I'd like two have two different python environments, one for `mbed-cli` and another one for `ROS`. I'm still new to nix but I think the best practice would be to call `mkPython` twice by doing something like:
```
mbed-cli = mach-nix.mkPython {
    requirements = ''
      # mbed-cli
      mbed-cli
      pip
      pyyaml
      jsonschema
      jinja2
      mbed_cloud_sdk
      pyelftools
      mbed_ls
      manifest_tool
      pycryptodome
      pyusb
      psutil
      click
      ";

ros = mach-nix.mkPython {
    requirements = ''
      # ROS
      rosdep
      rosinstall-generator
      vcstool
      rosinstall
      setuptools
      empy
    '';
```
Unfortunately that doesn't work, and I believe it could be solved if I pass a different name attribute to each of them.

**Comment by DavHau** [comment]
You can call mkPython as often as you want. The snippet you shared is totally valid if put inside a `let ... in` block.
The more relevant question is. what would you like to do with these two environments?
Are you actually interested in using everything from that python environment, or are you only interested in one particular cli application? In the latter case, you may consider using `buildPythonApplication` instead of `mkPython`.

For mbed-cli the following should work for example:
```nix
mach-nix.buildPythonApplication {
  src = builtins.fetchTarball {
    url = "https://github.com/ARMmbed/mbed-cli/tarball/1.10.4";
    sha256 = "1l8j31b0ra57y5mjmb3fa64ywpyz6m7rwbxhilpayx8ih2vhgdfx";
  };
}
```

Please see the examples for [buildPythonPackage / buildPythonApplication](https://github.com/DavHau/mach-nix/blob/master/examples.md#buildpythonpackage--buildpythonapplication) and let me know if something is unclear there.

**Comment by tartavull** [comment]
Works beautifully, thank you mach-nix and your time to explaining me how to use it.

Cheers,
Ignacio
