### ISSUE TITLE
support (or ignore?) other requirements.txt parameters

### ISSUE THREAD

**Issue by abathur** [DavHau/mach-nix#21]
I saw you released a new version so I decided to give mach-nix a quick try, but I noticed some errors on a few flags used in our requirements.

1. We have a private index added by something like `--extra-index-url <private index url>` near the top of our requirements. The primary error looks like:

    ```
    Traceback (most recent call last):
      File "/nix/store/sl2pdxfyr6053a1p0af3lxscca3r101w-python3-3.7.6-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in __init__
        super(Requirement, self).__init__(requirement_string)
      File "/nix/store/sl2pdxfyr6053a1p0af3lxscca3r101w-python3-3.7.6-env/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'--extra-'"
    ```

2. We use the `--no-binary` flag for psycopg2 to workaround some SSL issue. I have this on the same line as the psycopg2 entry for documentation, but I guess given its syntax that it could appear on a line by itself: `psycopg2==2.7.5 --no-binary psycopg2`. This yields an InvalidRequirement error at the same location.

**Comment by DavHau** [comment]
If I'm not mistaken, both flags seem to be pip specific features which are not in any PEP specification. It looks like pip allows you to pass any pip cmdline arguments via requirements.txt.

Of course it might be worthwhile to support as much as pip supports, since this is what people are used to.

Is the extra index you are using a pypi clone or does it contain packages which are not on pypi? The way mach-nix accesses the pypi index is by having a full offline copy of URLs and hashes of all files.
If your index provides packages which are currently unknown to mach-nix then you would first have to crawl that index and provide it to mach-nix via json. But this step would need to be repeated once there are new libraries. Theoretically it would be possible to add a cmdline helper utility for including extra indexes. Do you think it's worth it?

The current alternative would be to remove `--extra-index-url` from your requirements.txt and add the packages from this source manually via `overrides_pre`. Then let mach-nix resolve the requirements.

`--no-binary` could easily be supported. It is equivalent for calling mach-nix  without using the wheel provider. I'm noticing that there currently is no clean way of blacklisting providers globally. A blacklisting feature should at least be added.

**Comment by abathur** [comment]
> Is the extra index you are using a pypi clone or does it contain packages which are not on pypi? The way mach-nix accesses the pypi index is by having a full offline copy of URLs and hashes of all files.

It's a [private index hosted on gemfury](https://gemfury.com/l/pypi-server) which for now just has a single private/internal extension.

> If your index provides packages which are currently unknown to mach-nix then you would first have to crawl that index and provide it to mach-nix via json. But this step would need to be repeated once there are new libraries. Theoretically it would be possible to add a cmdline helper utility for including extra indexes. Do you think it's worth it?

Not sure I can speak to the utility for users who add multiple indexes or indexes with many packages. 

In our case, since it's just one index with one package, I think a few fairly manual setup steps would be fine as long as they're clear/obvious and wouldn't need to be repeated each time a new package _version_ is released?

> The current alternative would be to remove `--extra-index-url` from your requirements.txt and add the packages from this source manually via `overrides_pre`. Then let mach-nix resolve the requirements.

Not sure if the ergonomics of this would be quite enough for my case? I'll describe my ~goal (not that you need to meet it--just so it's clear where I'm coming from and trying to end up) between the horizontal rules below, and after the 2nd rule I'll circle back to how I interpret your comment above.

----
We deploy a Python app on Heroku; historically we developed in Vagrant/VirtualBox. I've moved _my_ dev environment to a shell.nix + requirements.nix generated via `pypi2nix` and heavily hand-customized to fix many issues to get it running (plus minor ongoing updates since then). 

I'd like to move everyone eventually so that I don't have to maintain both environments, but I have concerns with my Nix setup:
1. It's got ~90 expressions to cover the graph, compared to ~26 in the .txt (a few of which are sub-dependencies added to fix a bug or get a feature and could be dropped later). Small version bumps of specific dependencies have been manageable, but I imagine large, broad, and frequent updates will all be painful (and I may occasionally have to drop what I'm doing to do this work for an update someone else needs).
2. With both the .nix and .txt hand-updated, there isn't a single authoritative package spec; drift will inevitably creep in between the .nix and requirements.txt (unless I find a good way to write a test blocks drift?)
3. _I_ am not terribly picky about whether .nix or .txt is authoritative, but making the .nix authoritative will be a hurdle to others when they want to do something simple in pip-land--like add a few packages to see which solves a specific problem best, but find one or more aren't already in Nixpkgs and need a new expression.

So I've been keeping tabs on mach-nix since you posted on discourse--at least in the abstract I imagine a reliable way to build the Nix expressions from the requirements.txt would solve the ergonomics concerns I have, making it possible to move development over to Nix but keep the authoritative spec in the .txt.

----
I can imagine using grep to filter out the `--extra-index-url <url>` and the package installed from that index in order to feed the remaining requirements to mach-nix from an fd or temp file. I think that would be a big improvement for maintaining most of the package set, but I'm a little concerned about building a workflow that makes it look like requirements.txt is authoritative by doing a little magic to hide the fact that it is not-quite-authoritative?

If the improvement from the former is big enough, I assume I'd find the motivation to at least try hacking in a pre-process step to extract the private package version from the .txt and generates/edits a .nix override for the package.

**Comment by DavHau** [comment]
> I'd like to move everyone eventually so that I don't have to maintain both environments, but I have concerns with my Nix setup:
> 
> 1. It's got ~90 expressions to cover the graph, compared to ~26 in the .txt (a few of which are sub-dependencies added to fix a bug or get a feature and could be dropped later). Small version bumps of specific dependencies have been manageable, but I imagine large, broad, and frequent updates will all be painful (and I may occasionally have to drop what I'm doing to do this work for an update someone else needs).
> 1. With both the .nix and .txt hand-updated, there isn't a single authoritative package spec; drift will inevitably creep in between the .nix and requirements.txt (unless I find a good way to write a test that blocks drift?)
> 1. I am not terribly picky about whether .nix or .txt is authoritative, but making the .nix authoritative will be a hurdle to others when they want to do something simple in pip-land--like add a few packages to see which solves a specific problem best, but find one or more aren't already in Nixpkgs and need a new expression.

Concern 1 should be resolved by mach-nix and concern 2 & 3 are also solved as soon as you switch everyone to nix. You only have this issues because you try to keep both worlds.

Currently you could maybe make it easier by splitting up your requirements.txt into two files. One file which can be understood by mach-nix and the other part which contains the packages coming from non-pypi sources or packages requiring pip specific flags
Only for that second part you then would need to create an overlay for mach-nix which adds the missing parts.
If you show me the requirements.txt I can try to help with that.
As said, the `--no-binary` could be supported by mach-nix. Feel free to file a PR if you feel like it.

**Comment by DavHau** [comment]
Closing this, since I'm not really planning to add pip specific feature to the requirements.txt.

Since mach-nix 2.3.0, extra packages from arbitrary sources can be added via `extra_pkgs` argument.
