### ISSUE TITLE
requirements from pypi-deps-db prioritized over specified provider

### ISSUE THREAD

**Issue by kini** [DavHau/mach-nix#270]
When using mach-nix to install a Python package and specifying its provider as "nixpkgs", the dependency resolution logic appears to prioritize computed information from pypi-deps-db even if the Nix expression in nixpkgs for the package has changed the requirements for the package to something else.

For example, the aws-sam-cli expression in nixpkgs changes its requirements.txt to replace `docker~=4.2.0` with `docker>=4.2.0`, which allows it to build with the current version of the docker package in nixpkgs, which is 4.4.4.

So the `shell.nix` file is able to combine the requirements `aws-sam-cli==1.23.0` and `docker==4.4.4`, as long as I also set the provider for aws-sam-cli to "nixpkgs":

```nix
{ pkgs ? import <nixpkgs> { } }:

with pkgs; let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix";
    ref = "refs/tags/3.2.0";
  }) {
    # currently aws-sam-cli is a standalone `buildPythonApplication`
    # in nixpkgs; the commit below includes changes which put
    # aws-sam-cli into python3Packages as a `buildPythonPackage`,
    # which makes it visible to mach-nix.  See
    # https://github.com/NixOS/nixpkgs/pull/121716
    pkgs = import (fetchFromGitHub {
      owner = "kini";
      repo = "nixpkgs";
      rev = "bc4048a95f6177b67aecd7622e7fcce650cfed61";
      sha256 = "1mn1hbjx173708nmyvnddjlshh50d9rfhbh5czc1c7fg6z5k8i0h";
    }) { };

    # pypiDataRev = "bb1a875a427e41bf331a7ec8214d5ea9eabc0b16";
    # pypiDataSha256 = "0fjqq49wqy9phavzgiis4d5cnax2zqx472zz0iij757q15ql2z8b";
  };

in mkShell rec {
  buildInputs = [(mach-nix.mkPython {
    requirements = ''
      aws-sam-cli==1.23.0
      docker==4.4.4
    '';
    providers.aws-sam-cli = "nixpkgs";
  })];
}
```

(See NixOS/nixpkgs#121716 for information about the `pkgs =` line.)

But if I uncomment the `pypiDataRev` and `pypiDataSha256` lines in the above `shell.nix`, I get the following error:

```
building '/nix/store/7d1s8f7ir8ilv2mngl5wwcaxcpaqn80s-mach_nix_file.drv'...

Some requirements could not be resolved.
Top level requirements:
  aws-sam-cli==1.23.0  docker==4.4.4
Providers:
  {'_default': 'wheel,sdist,nixpkgs',
   'aws-sam-cli': 'nixpkgs',
   'gdal': 'nixpkgs',
   'pip': 'nixpkgs,sdist',
   'setupmeta': 'wheel',
   'setuptools': 'nixpkgs',
   'wheel': 'nixpkgs,sdist'}
Mach-nix version: 3.2.0
Python: 3.8.9
Cause: None
The requirements which caused the error:
  docker==4.4.4
  docker==4.2.*,>=4.2.0 - parent: aws-sam-cli:1.23.0

builder for '/nix/store/7d1s8f7ir8ilv2mngl5wwcaxcpaqn80s-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/7d1s8f7ir8ilv2mngl5wwcaxcpaqn80s-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)
```

mach-nix 3.2.0 was released before aws-sam-cli 1.23.0, so I guess the default pypiDataRev doesn't contain information about aws-sam-cli 1.23.0. But the pypiDataRev I'm explicitly providing was snapshotted from PyPI after aws-sam-cli 1.23.0 was released, so I'm guessing that mach-nix is incorrectly prioritizing the requirements information from pypi-deps-db (`docker~=4.2.0`) rather than the real requirements of the package being built (`docker>=4.2.0`).

**Comment by jonringer** [comment]
why don't you just put `aws-sam-cli` as a buildInput (outside of `mkPython`), then you can just use it as the command line tool. I don't see anywhere in https://docs.aws.amazon.com/serverless-application-model/ where they intend for it to be used as a module.

**Comment by kini** [comment]
Putting `aws-sam-cli` in `buildInputs` directly will set `$PYTHONPATH` inside the nix-shell environment, which can conflict with the versions of things in the environment produced by `mkPython`. Admittedly I'm not sure why `$PYTHONPATH` is being set in this case, since I'd think a `buildPythonApplication` like `aws-sam-cli` should be self-contained.

But anyway, I don't think the issue I'm reporting here is specific to `aws-sam-cli` - it's just an example of the general issue, I would assume, though I haven't tried it with other packages whose nixpkgs expression has different dependency info from what pypi-deps-db has.

**Comment by jonringer** [comment]
> Putting `aws-sam-cli` in `buildInputs` directly will set `$PYTHONPATH` inside the nix-shell environment,

Hmm, I have confirmed that is happening. But it shouldn't :(

**Comment by kini** [comment]
I was led to believe by comments on NixOS/nixpkgs#26146 that this was intended behavior, though I don't know if anything has changed since then.

**Comment by jonringer** [comment]
this probably has to do with the behavior of `propagatedBuildInputs`. This would probably be solved by https://github.com/NixOS/nixpkgs/pull/102613. However, it would be a major paradigm shift.

**Comment by kini** [comment]
To clarify, by "this" do you mean the issue with `buildPythonApplication` expressions being put in a `mkShell`'s `buildInputs` leading to a polluted `$PYTHONPATH`? Or do you mean this issue (DavHau/mach-nix#270) about mach-nix prioritizing pypi-deps-db over dependency information extractable from a nixpkgs python-modules expression?

**Comment by jonringer** [comment]
The former. Pollution of the $PYTHONPATH.

**Comment by DavHau** [comment]
The behavor you're experiencing is intentional. If mach-nix has data about a package in its DB, it will always build its dependency tree from this data instead of following nixpkgs. Mach-nix will only fall back to following nixpkgs when it doesn't have the data.
There are some reasons not to blindly trust the nixpkgs dependency tree. See [this for example](https://discourse.nixos.org/t/python-package-rodeo/12282/5?u=davhau).
Dependency trees in nixpkgs are often incomplete whenever tests are disabled, which they are in our case by default.

If we would want to take the nixpgs tree instead, the question arises, how would we even do that?
How could mach-nix discover that `docker~=4.2.0` has been re-defined to `docker>=4.2.0`? It could happen through some patch, or some script in patchPhase. There is no fixed standard about this. Mach-nix can only see that the nixpkgs candidate depends on docker version `4.4.0`. Should we assume this means `==4.4.0` ? What if you would like to use docker `docker~=4.3.0`. Should that be allowed? I guess you can see where I'm heading.
I think in general the data from the dependency DB is the most reliable and in the majority of cases it's a good decision to follow this data.

If you have any idea on how to manage this better, I'm happy to discuss about it.

I have been thinking about adding a feature that allows to to inject or force specific edges into the dep tree. Something like:

```
forceDependencies = {
  aws-sam-cli = "docker==4.4.4"
};
```

**Comment by kini** [comment]
Thanks for the explanation! That's a good point about how the nixpkgs information can only give precise versions like `==4.4.0`.

I agree that it would be nice to have a way to manually override the dependency graph as you suggest.

**Comment by DavHau** [comment]
Just to clarify. The reason why your example works when not setting pypiDataRev is becuase mach-nix doesn't have data about your package and therefore doesn't touch the nixpkgs dependency tree. It sees that package as a black box. That works out in your case but in other situation that could lead to problems.

If you use mach-nix via the flakes interface, your expression wouldn't even evaluate because it will detect that your pypiData is older than nixpkgs, and warn your. I added that recently to prevent exactly that kind of  situations with undefined behavior.

Sadly I cannot add this warning to the legacy api becuse there is no way of determining the release date of nixpkgs when imported via fetchTarball etc.

**Comment by kini** [comment]
> and therefore doesn't touch the nixpkgs dependency tree

I'm not sure what you mean by this - clearly `aws-sam-cli`'s dependencies needed to be installed somehow, right? Do you mean that if there were other packages involved which mentioned some of `aws-sam-cli`'s dependencies in their own requirements, that mach-nix wouldn't attempt to reconcile the version ranges for those dependencies with the real versions found in the nixpkgs tree?

**Comment by DavHau** [comment]
If it doesn't have any data about a aws-sam-cli, but it finds aws-sam-cli in nixpkgs, it considers it a leaf in the dependency tree and totally disragards the dependencies of that package. It just inherits this package as is from nixpkgs. This package, of course, comes with dependencies, but the resolver itself is not aware of these and wouldn't raise an error even if you would define some other version for any of `aws-sam-cli`'s dependencies in your requirements.

In that case, you would end up with a package collision since you have two different versions in your closure. The one defined in your requirements, and the one, indirectly inherited from nixpkgs.

BUT. There are some sneaky hacks in the mach-nix generated nix expression, which prevent these collisions. For all packages which have been taken from nixpkgs, it will recusively replace their dependencies, IF and only if another package with the same normalized name has been defined by mach-nix.

In the end this is a best effort approach, wich works in most of the cases. But I think using the DB is better.

**Comment by kini** [comment]
Interesting, thanks for the insight into what is going on in the guts of mach-nix :)

**Comment by DavHau** [comment]
I wish this was less complex :) But sadly it isn't.
