### ISSUE TITLE
Can't import modules from packages created by mach-nix

### ISSUE THREAD

**Issue by korayal** [DavHau/mach-nix#282]
I'm not sure if I'm doing things correctly, but I have [a demo project](https://github.com/korayal/mach-nix-demo) that uses mach-nix to create a nix-derivation. When I drop into the shell, I am able access the package inside iPython.

But when I try loading it inside an environment with `python37.withPackages` as below I can't see my modules:

```
nix-shell -p 'with import (fetchTarball "https://github.com/korayal/mach-nix-demo/archive/master.tar.gz") {}; python37.withPackages (ps: with ps; [ ipython demo-library ])' --run ipython
```

Does this mean I'm using mach-nix wrong?

**Comment by DavHau** [comment]
The `./demo` directory in your repo is not a valid python module (It doesn't have a __init__.py file). Therefore `find_packages()` in your setup.py doesn't find any modules. As a result, only metadata is installed, but no python files.

**Comment by DavHau** [comment]
In general it should work. The problem might be that your nixpkgs' python3 defaults to another python version than the one from mach-nix. That could be fixed by passing `pkgs` when importing mach-nix.

But it is usualy not agod idea to mix mach-nix generated python packages with the ones from nixpkgs. There is no guarantee that your python packages will be compatible. Also collisions will be likely since both sides might depend on different versions of the same libs.

It's best to always use mach-nix.mkPython and include external packages via `packagesExtra`

**Comment by korayal** [comment]
Thank you for your insight. it seems I've misinterpreted the use case of mach-nix. closing the issue.
