### ISSUE TITLE
environment from .nix file - no access to specified config - python 2.7 from home-manager

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#72]
env after

nix-shell shell_mach-nix__test.nix

```
let
  #mach-nix = import (builtins.fetchGit {
  #  url = "https://github.com/DavHau/mach-nix/";
  #  ref = "refs/tags/2.2.1";
  #  #ref = "2.2.1";
  #});

  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "dev";
    rev = "371c0ebf7d6629c6893bc140be541452b2bd3129";
  });

  pkgs = import <nixpkgs> { config = { allowUnfree = true; };  };
in mach-nix.mkPython  rec { 

  python = pkgs.python38;

  requirements = ''
     # your requirements here
     dask==2.22.0
     pyct==0.4.6
     rasterio==1.1.5
     numba==0.50.1
     arcgis==1.8.2
     datashape==0.5.2
  '';
}
```

show not the speficied python version?

```
nix-shell shell_mach-nix__test.nix --show-trace
[nix-shell:] which python 
/home/user/.nix-profile/bin/python
# [nix-shell:} ls -lah /home/user/.nix-profile/bin/python
lrwxrwxrwx 1 root root 72 Jan  1  1970 /home/user/.nix-profile/bin/python -> /nix/store/5rzsb9q7v4qzbgwz3pp6kfzkf48kyzq8-home-manager-path/bin/python
[nix-shell:] python --version
Python 2.7.18
```

**Comment by tfmoraes** [comment]
It's happening to me too. If I use the same shell.nix from the readme, when I enter in the nix-shell the Python is same from home-manager:

```
❯ nix-shell
❯ which python
/home/thiago/.nix-profile/bin/python
```
But calling Nix-shell using the `-p` parameter it works correctly (but it not uses my shell.nix expression):

```
❯ nix-shell -p 'python38.withPackages (ps: with ps; [ ps.pillow ps.numpy ps.requests ])'
❯ which python
/nix/store/0m2jb5dn69wvisvd5mjs96pn4jz1vn4c-python3-3.8.5-env/bin/python
```

**Comment by DavHau** [comment]
You need to use `mach-nix.mkPythonShell` instead of `mach-nix.mkPython`

Why?
The problem is, that `mkPython` returns a normal derivation.
The original purpose of the nix-shell command is to debug the build of a derivation. Therefore [as of the official nixos docs](https://nixos.org/nix/manual/#description-13), in order to be able to do this:
`The command nix-shell will build the dependencies of the specified derivation, but not the derivation itself.`

To really load a derivation with nix-shell, you need to make another derivation which has your original derivation as `buildInput`. This is what `mkShell` from nixpkgs and `mkPythonShell` from mach-nix are doing.
