### ISSUE TITLE
version constraints

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#85]
why does  `jupyterlab_code_formatter` forces the resolver to downgrade `jupyterlab` to 1.2.16

```
jupyterlab_code_formatter
jupyterlab >= "^2.2.0"
pandas
ipython
```

**Comment by InLaw** [comment]
jupyterlab>=2.2.0
is recognized correctly

eaven so, the format was misunderstood, why not resolving to the max available version?

**Comment by DavHau** [comment]
"^2.2.0" is invalid due to python standards AFAIK. It is a poetry custom format.
The requirements.txt native notation to achieve the same behaviour is:
`jupyterlab ~= 2.2.0`
Poetry's format is based on toml and toml doesn't allow `~=`. Therefore I guess they invented `"^x.x.x"`.

Concerning the other question: "Why does the resolver pick an old version by default":
I don't know exactly. In general dependency resolution is an NP hard problem and it cannot be guaranteed that a resolution will be perfect.
There is a jungle of constraints and the resolver tries to find a somehow easy path through it. Jupyterlab "2.2.0" might introduce additional constraints which make going that way more complicated, so the resolver decides to not go there.

It would be interesting to see which versions the new pip picks, since it is basically using the same algorithm.
Mach nix is one version behind, using resolvelib "0.3.0", while pip uses "0.4.0". Maybe upgrading could improve it.
I haven't been prioritizing to implement 0.4.0, since 0.3.0 works quite well, as far as I can tell and updating to 0.4.0 involves some work, since the interface changed. Feel free to look into it if you like.

**Comment by InLaw** [comment]
Well if you don't dare to check and merge the little [nixkgsVersion](https://github.com/DavHau/mach-nix/pull/107) it wouldn't make to much sense to invest into a bigger change .. would it?
- it's great to see how fast and progressiv you are driving the project. On the other hand if requests don't get attention there would be shortly again lots of changes to fit the new state of the project

**Comment by DavHau** [comment]
It don't see why the PR should be related to the current issue. Updating nixpkgs probably wouldn't change anything with the current problem. Mach-nix uses a relatively new version of nixpkgs and pypi-deps-db anyways. I update them every now and them when I do a release.
The problem mach-nix not picking jupyterlab 2.x.x automatically is not because it is not available. It's just because the resolver doesn't decide to pick it. If you set `jupyter ~= 2.2.0`, it will pick a recent version.

The reason I didn't merge the PR so far is because I think it still requires some work. (see my comments in the PR).
I took a look again now and noticed, that it would probably be a good idea to also use the same method to update the pypi-deps-db. Probably that would be even more important than updating nixpkgs. Since most people might be more interested in recent pypi releases, compared to what is going on in nixpkgs. Nixpkgs never has the newest stuff anyways.

**Comment by InLaw** [comment]
it is not related to the issue

----- 

it is a question of why doing a effort 

-> I cannot see any comment in the PR

---

even the feature to change the commit of the pypi-db could be more useful 
the functionality has nothing common with changes to nixpkgs (these are totally separate functionalites)

**Comment by DavHau** [comment]
Just noticed, that you probably didn't see my comments because I didn't click "finish your review". You can see, I'm not a github pro. I'm very sorry!
