### ISSUE TITLE
pkg: pylantern / cufflinks

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#90]
```
builder for '/nix/store/1w5bap1xrab45fm526rl47zm286p4g74-python3.7-cufflinks-0.17.3.drv' failed with exit code 1
cannot build derivation '/nix/store/af4rcm6x6c5gq18gbc0zgx7yxzxhiz49-python3-3.7.6-env.drv': 1 dependencies couldn't be built
error: --- Error --- nix-shell
```

**Comment by DavHau** [comment]
I cannot reproduce the error. Please always append reproducible nix expression which triggers the error.
The following builds fine for me:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "2.2.2";
  });
in mach-nix.mkPython rec {
  requirements = ''
    cufflinks
  '';
}
```

**Comment by InLaw** [comment]
```
let
   mach-nix = import (builtins.fetchGit {
     url = "https://github.com/DavHau/mach-nix/";
     #ref = "dev";
     ref = "2.2.2";
     rev = "371c0ebf7d6629c6893bc140be541452b2bd3129";
   });

   overlays = []; # some very useful overlays
  pkgs = import <nixpkgs> { config = { allowUnfree = true; }; inherit overlays; };
in mach-nix.mkPythonShell rec {
  python = pkgs.python37;
  requirements =  ''  pylantern  '';

}
```

**Comment by DavHau** [comment]
The `<nixpkgs>` from `import <nixpkgs>` refers to your local nixpkgs channel. I cannot reproduce this since i don't know your nixpkgs channels version.

In general it's best to avoid passing your own `pkgs` if you don't really have to.
If you need to change the config of nixpkgs ( to set allowUnfree for example) or you need to include your own overlays, it's always better to do this ontop of the nixpkgs version which is used by mach-nix.

You can can refer to the nixpkgs source of mach-nix via `mach-nix.nixpkgs.path`.
In you specific example the nixpkgs import could look like this:
```nix
pkgs = import mach-nix.nixpkgs.path { config = { allowUnfree = true; }; inherit overlays; };
```
With this your expression successfully builds.

I will replace the example in examples.md to also do it the proper way.

**Comment by InLaw** [comment]
it works for 

`ref = "refs/tags/2.2.2"; `

(without rev specified)
